name: Build Extension
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm run build
      - run: npx @anthropic-ai/dxt pack
      - uses: actions/upload-artifact@v3
        with:
          name: canvas-mcp-extension
          path: '*.dxt'