name: Release
on:
  push:
    tags: ['v*']

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install && npm run build
      - run: npm install -g @anthropic-ai/dxt && dxt pack
      - uses: softprops/action-gh-release@v1
        with:
          files: '*.dxt'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}